=== EuropeanSpallationSource/openxal/core/src/main/resources/xal/schemas/model-impl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">

    <xs:complexType name="className">
        <xs:attribute name="type" type="xs:string" use="required"/>
    </xs:complexType>
		
    <xs:complexType name="associations-map">		
        <xs:attribute name="smf" type="xs:string" use="required"/>
        <xs:attribute name="model" type="xs:string" use="required"/>	
    </xs:complexType>
	
    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="elements">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="default" type="className"/>
                            <xs:element name="drift" type="className"/>
                            <xs:element name="rfcavdrift" type="className" minOccurs="0"/>
                            <xs:element name="sequence" type="className" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="associations">
                    <xs:annotation>
                        <xs:documentation>
                            Implementation: xal.sim.cfg.ArchiveItemList<br/>
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="map" type="associations-map" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== EuropeanSpallationSource/openxal/test/src/test/resources/xal/schemas/modelconfig_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="model-impl.xsd">
    <elements>
        <default type="fake.package.model.Default"/>
        <drift type="fake.package.model.Drift"/>
        <rfcavdrift type="fake.package.model.RfCavDrift"/>
        <sequence type="fake.package.model.Sector"/>
    </elements>
    <associations>
        <map smf="fake.package.Map1" model="fake.package.model.Map1"/>
        <map smf="fake.package.Map2" model="fake.package.model.Map2"/>
        <map smf="fake.package.Map3" model="fake.package.model.Map3"/>
    </associations>
</configuration>

=== EuropeanSpallationSource/openxal/extensions/jels/src/main/resources/xal/extension/jels/mainModelConfig.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="https://bitbucket.org/europeanspallationsource/openxal/raw/site.ess.master/core/resources/xal/schemas/model-impl.xsd"
               subsectionCtrOrigin="false">
               
    <elements>
        <default type="xal.model.elem.Marker"/>
        <drift type="xal.model.elem.IdealDrift"/>
        <rfcavdrift type="xal.model.elem.IdealRfCavityDrift"/>
        <sequence type="xal.model.Sector"/>
    </elements>
    
    <associations>
        <map smf="fm" model="xal.extension.jels.model.elem.FieldMap"/>
        <map smf="sfm" model="xal.extension.jels.model.elem.SolFieldMap"/>
        <map smf="mfm" model="xal.extension.jels.model.elem.MagFieldMap3D"/>
        <map smf="dh" model="xal.extension.jels.model.elem.IdealMagWedgeDipole2"/>
        <map smf="q" model="xal.model.elem.IdealMagQuad"/>
        <map smf="qt" model="xal.model.elem.IdealMagQuad"/>
        <map smf="pq" model="xal.model.elem.IdealMagQuad"/>
        <map smf="dch" model="xal.model.elem.IdealMagSteeringDipole"/>
        <map smf="dcv" model="xal.model.elem.IdealMagSteeringDipole"/>
        <map smf="rfgap" model="xal.extension.jels.model.elem.IdealRfGap"/>
        <map smf="marker" model="xal.model.elem.Marker"/>
        <map smf="DTLTank" model="xal.model.elem.IdealRfCavity"/>
    </associations>
</configuration>

=== EuropeanSpallationSource/openxal/extensions/jels/src/test/resources/xal/extension/jels/lattice0/mainModelConfig.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="https://bitbucket.org/europeanspallationsource/openxal/raw/site.ess.master/core/resources/xal/schemas/model-impl.xsd"
               subsectionCtrOrigin="false">
   
    <elements>
        <default type="xal.model.elem.Marker"/>
        <drift type="xal.model.elem.IdealDrift"/>
        <rfcavdrift type="xal.model.elem.IdealRfCavityDrift"/>
        <sequence type="xal.model.Sector"/>
    </elements>
    
    <associations>
        <map smf="rfm" model="xal.extension.jels.model.elem.ThickRfFieldMap"/>
        <map smf="mfm" model="xal.extension.jels.model.elem.ThickMagFieldMap"/>
        <map smf="d" model="xal.extension.jels.model.elem.IdealMagWedgeDipole"/>
        <map smf="q" model="xal.model.elem.IdealMagQuad"/>
        <map smf="pq" model="xal.model.elem.IdealMagQuad"/>
        <map smf="dc" model="xal.model.elem.IdealMagSteeringDipole"/>
        <map smf="rg" model="xal.extension.jels.model.elem.IdealRfGap"/>
        <map smf="marker" model="xal.model.elem.Marker"/>
        <map smf="rf" model="xal.model.elem.IdealRfCavity"/>
        <map smf="DTLTank" model="xal.model.elem.IdealRfCavity"/>
        <map smf="rfq" model="xal.extension.jels.model.elem.RfqDummyModel"/>
    </associations>
</configuration>
